### ISSUE TITLE
Application error when starting with OpenAPI Spec documents

### ISSUE THREAD

**Issue by AtjonTV** [ArchGPT/insomnium#51]
### Expected Behavior

OpenAPI Spec documents are loaded correctly, and the Application is usable.

### Actual Behavior

The following error occurres, and the Application is unusable.
```
TypeError: t.spec.info.version.startsWith is not a function
    at children (file:///tmp/.mount_Insomn2Jv1B2/resources/app.asar/project-31d5e5ef.js:10:27884)
    at file:///tmp/.mount_Insomn2Jv1B2/resources/app.asar/index-62719d76.js:197:9275
    at Object.useMemo (file:///tmp/.mount_Insomn2Jv1B2/resources/app.asar/index-62719d76.js:38:25888)
    at w2.useMemo (file:///tmp/.mount_Insomn2Jv1B2/resources/app.asar/index-62719d76.js:9:6238)
    at Ns (file:///tmp/.mount_Insomn2Jv1B2/resources/app.asar/index-62719d76.js:197:9182)
    at GCe (file:///tmp/.mount_Insomn2Jv1B2/resources/app.asar/index-62719d76.js:197:9613)
    at ZCe (file:///tmp/.mount_Insomn2Jv1B2/resources/app.asar/index-62719d76.js:197:9989)
    at i7 (file:///tmp/.mount_Insomn2Jv1B2/resources/app.asar/index-62719d76.js:197:9737)
    at Swe (file:///tmp/.mount_Insomn2Jv1B2/resources/app.asar/index-62719d76.js:197:24092)
    at RC (file:///tmp/.mount_Insomn2Jv1B2/resources/app.asar/index-62719d76.js:38:19553)
  ```

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Additional Information

This issue has already been fixed in Insomnia 8.0 with this commit: https://github.com/Kong/insomnia/commit/368c34f27bd2829878dd73fffb4d12382fa5ba9e

The simplest solution would be to port that commit to Insomnium.

### Insomnium Version

0.2.1-b

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux (Kernel: 6.5.6)

### Installation method

AppImage

**Comment by archywillhe** [comment]
aw thanks for the pointer I'll merge the commit to Insomnium in the release
